// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/menu-nav/Aktuell.tsx": () => import("../components/mockups/menu-nav/Aktuell.tsx"),
  "./components/mockups/menu-nav/Vorschlag.tsx": () => import("../components/mockups/menu-nav/Vorschlag.tsx"),
  "./components/mockups/admin-dienstplan/MobileKalender.tsx": () => import("../components/mockups/admin-dienstplan/MobileKalender.tsx")
};
