// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dienstplan-leiste/AktionenUnten.tsx": () => import("../components/mockups/dienstplan-leiste/AktionenUnten.tsx"),
  "./components/mockups/dienstplan-leiste/MonatOben.tsx": () => import("../components/mockups/dienstplan-leiste/MonatOben.tsx")
};
